### ISSUE TITLE
Create a txt file

### ISSUE THREAD

**Issue by dmolner** [potsky/Netatmo#16]
Hello,

Great work.
Is possible create a txt file with all values with your php page ?

Best Regards,
David.

**Comment by potsky** [comment]
Hello,

I just a push a new commit with the `text.php` script. Update the repo and execute this script. You should be able to parse values easily.

Tell me if you need something else ;-)

**Comment by dmolner** [comment]
Hello,
Thank you for your help.
I see these lines.
Could you explain because some part are repeated?

`id|xx:xx:xx:xx:xx:xx
name|Modul exterior
time|1487370897
time_utc|1487370897
Temperature|10,4
Humidity|71
date_max_temp|1487333009
date_min_temp|1487317218
min_temp|8,5
max_temp|29,9
Temperature|10,4
Humidity|71
CO2|
Rain|
min_temp|8,5
date_min_temp|1487317218
max_temp|29,9
date_max_temp|1487333009
min_hum|29
date_min_hum|1487336034
max_hum|88
date_max_hum|1487298710
sum_rain|
sum_rain_1|
sum_rain_24|
WindStrength|
WindAngle|
id|xx:xx:xx:xx:xx:xx
name|Anenometre
time|1487370923
WindAngle|-1
WindStrength|0
GustAngle|90
GustStrength|1
time_utc|1487370923
WindHistoric|Array
date_max_wind_str|1487334233
date_max_temp|1487286021
date_min_temp|1487286021
min_temp|0
max_temp|0
max_wind_angle|219
max_wind_str|9
Temperature|0
Humidity|0
CO2|
Rain|
min_temp|
date_min_temp|
max_temp|
date_max_temp|
min_hum|
date_min_hum|
max_hum|
date_max_hum|
sum_rain|
sum_rain_1|1
sum_rain_24|190
WindStrength|9
WindAngle|219
id|xx:xx:xx:xx:xx:xx
name|Pluviometre
time|1487370923
time_utc|1487370923
Rain|0
sum_rain_24|0
sum_rain_1|0
Temperature|
Humidity|
CO2|
Rain|0
min_temp|
date_min_temp|
max_temp|
date_max_temp|
min_hum|
date_min_hum|
max_hum|
date_max_hum|
sum_rain|0
sum_rain_1|
sum_rain_24|
WindStrength|
WindAngle|
`

**Comment by potsky** [comment]
These values comes from the Netatmo API in a raw format.

All informations about the api are available here : <https://dev.netatmo.com>

and especially here : <https://dev.netatmo.com/dev/resources/technical/reference/weatherstation/getstationsdata>

**Comment by dmolner** [comment]
OK.

Thankyou for all.
