### ISSUE TITLE
Array ( [code] => 26 [message] => User usage reached )

### ISSUE THREAD

**Issue by dtudtu** [potsky/Netatmo#18]
Hi Potsky,

first of all: great job, thank you!

Everthing is working fine, but after a few hours I´m getting this error message:
Array ( [code] => 26 [message] => User usage reached )
When this happens, I seems that my netatmo-account is "banned" for hours.

Any idea?

BR,
dtudtu

**Comment by potsky** [comment]
Indeed, there is a limit in the Netatmo API. That's why you need to install APC or APCu on PHP > 5.6. The widget will use APC to manage cache and avoid the reach limit.
