### ISSUE TITLE
invalid_client

### ISSUE THREAD

**Issue by naslada77** [potsky/Netatmo#21]
Hi!

I got invalid_client message. No messages in apache2 error log file. I use PHP7, Ubuntu server 16.04TLS.

cURL support | enabled
-- | --
cURL Information | 7.47.0
Age | 3
Features
AsynchDNS | Yes
CharConv | No
Debug | No
GSS-Negotiate | No
IDN | Yes
IPv6 | Yes
krb4 | No
Largefile | Yes
libz | Yes
NTLM | Yes
NTLMWB | Yes
SPNEGO | Yes
SSL | Yes
SSPI | No
TLS-SRP | Yes
HTTP2 | No
GSSAPI | Yes
KERBEROS5 | Yes
UNIX_SOCKETS | Yes
PSL | No
Protocols | dict, file, ftp, ftps,  gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp,  smb, smbs, smtp, smtps, telnet, tftp
Host | x86_64-pc-linux-gnu
SSL Version | OpenSSL/1.0.2g
ZLib Version | 1.2.8

**Comment by potsky** [comment]
Hi, the API is no more supported and the widget does not work anymore
